### ISSUE TITLE
Other installation issues

### ISSUE THREAD

**Issue by davidrigie** [VLOGroup/primal-dual-toolbox#2]
I ran into several things when installing this:

1. I had to have Eigen3 installed. On Ubuntu, this was resolved by: apt-get install libeigen3-dev 
2. It initially didn't work with my anaconda install built with python3.6. I had to create a new environment with python2.7
3. It couldn't find a file called "device_functions.hpp" In CUDA 9.1, this seems to have been renamed to "device_functions.h"

After that it works fine on my system!

**Comment by khammernik** [comment]
1. Added to install requirements for imageutilities in README.md
2. +3. were issues in the imageutilities and are fixed now.
